name: CI
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-26]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Select Xcode 26.2
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '26.2'
    - name: Install LLVM and Clang
      if: matrix.os == 'ubuntu-latest'
      run: |
        curl -L https://apt.llvm.org/llvm.sh | ALL=1 sudo bash -s 18
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-18 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-18 100
        sudo update-alternatives --install /usr/bin/llvm-config llvm-config /usr/bin/llvm-config-18 100
        sudo update-alternatives --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-18 100
        sudo update-alternatives --install /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-18 100
        sudo update-alternatives --install /usr/bin/llvm-nm llvm-nm /usr/bin/llvm-nm-18 100
    - name: Install dependencies
      run: npm install --omit=optional --build-from-source
    - name: Run test
      run: npm run test

  wasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - uses: mymindstorm/setup-emsdk@v14
      with:
        version: latest
    - name: Install dependencies
      run: npm install --omit=optional
    - name: Build WASM package
      run: npm run build-wasm
    - name: Build TypeScript
      run: npm run build-js
